### ISSUE TITLE
Backend/Wysiwyg Images

### ISSUE THREAD

**Issue by dni** [mVentory/MVentory_S3CDN#11]
Hi!

What about wysiwyg images, and backend images in general? After some fideling i was able to make it work, i uploaded the product images dimensions via the upload script to s3. then i changed the media storage and product images in FE are display correctly.

but now the crux.

If i upload a new image in the backend its not working. not even if i run the script again. So my customers cant even update the images anymore. Also all wysiwyg stuff isnt working also in BE/FE.

Is this in the scope of this extension? can i somehow help? i really wanna use a magento with fully integrated s3

**Comment by rimutaka** [comment]
Hi @dni, 

This extension was developed with our smartphone app  in mind.
We don't manage the images in the backend. They are taken by a smartphone or a DSLR camera, automatically uploaded to Mage and pushed to S3. There is no need for the back end functionality, but if  you can contribute some code to make it happen we are happy to help too.

Cheers,
Max

**Comment by rimutaka** [comment]
@dni , more info on the app is here http://mventory.com/product-management-app/

**Comment by dni** [comment]
i like it :) looks like a good solution

**Comment by dni** [comment]
@rimutaka so if BE isn't the main focus of your extension, i think i would be better to write something separate because i fear that making it work in the backend would be the biggest part of the extension.

If i have some time i will look at it more deeply, maybe it will fit.

**Comment by rimutaka** [comment]
Daniel, yes, sure. Feel free to fork this one too and let us know if you 
get BE or WYSIWYG to work.
