### ISSUE TITLE
Upload crashes everything

### ISSUE THREAD

**Issue by joshspivey** [mVentory/MVentory_S3CDN#8]
When I try to save after adding a image in the admin I get this error. 

[pool www] child 12040 exited on signal 11 (SIGSEGV) after 403.501871 seconds from start

and this is php -v

PHP 5.6.15 (cli) (built: Oct 31 2015 10:02:09) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v5.0.19, Copyright (c) 2002-2015, by ionCube Ltd.
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

**Comment by rimutaka** [comment]
Josh, sorry, can't help.
It works for us.

**Comment by NestorAcevedo** [comment]
That shows uploading the image takes more than 403 seconds to finish and the PHP max_execution_time is not set beyond that value, but that an image takes more than 5 minutes to be uploaded is because it is so heavy.
